# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 22:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actas_entrada')),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Acta de entrada',
                'verbose_name_plural': 'Actas de entradas',
            },
        ),
        migrations.CreateModel(
            name='ActaRequisicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Acta de requisici\xf3n',
                'verbose_name_plural': 'Actas de requisici\xf3n',
            },
        ),
        migrations.CreateModel(
            name='ActaSalida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actas_salida', verbose_name='Acta')),
                ('descripcion', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Acta de salida',
                'verbose_name_plural': 'Actas de salidas',
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=60)),
                ('activado', models.BooleanField(default=True)),
                ('vendido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activo Serial',
                'verbose_name_plural': 'Activos Seriales',
            },
        ),
        migrations.CreateModel(
            name='ActivoInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('serial', models.CharField(max_length=60)),
                ('activado', models.BooleanField(default=True)),
                ('vendido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Activo no serial',
                'verbose_name_plural': 'Activo no seriales',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('tiempo_entrega', models.IntegerField(verbose_name='Tiempo de entrega(Dias)')),
                ('activado', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
            options={
                'verbose_name': 'Articulo Piscina',
                'verbose_name_plural': 'Articulos Piscinas',
            },
        ),
        migrations.CreateModel(
            name='ArticuloInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(max_length=500)),
                ('activado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Articulo no serial',
                'verbose_name_plural': 'Aticulos no seriales',
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identi', models.CharField(max_length=45, verbose_name='Identificaci\xf3n')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Central',
                'verbose_name_plural': 'Centrales',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Custodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identi', models.CharField(max_length=45, verbose_name='Identificaci\xf3n')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='actas_entrada')),
                ('descripcion', models.TextField(max_length=500)),
                ('activos', models.ManyToManyField(to='inventario.ActivoInsumo')),
                ('custodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Custodio')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino1', to='inventario.Bodega')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen1', to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Entrada de Insumo',
                'verbose_name_plural': 'Entradas de Insimos',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActivoInsumo')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Log de Insumo',
                'verbose_name_plural': 'Logs de insumos',
            },
        ),
        migrations.CreateModel(
            name='LogPiscina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Articulo')),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Log piscina',
                'verbose_name_plural': 'Logs de piscinas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Provedores',
            },
        ),
        migrations.CreateModel(
            name='RequisicionArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActaRequisicion')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Articulo')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='RequisicionNoSerial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActaRequisicion')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ArticuloInsumo')),
            ],
            options={
                'verbose_name': 'Activo no serial',
                'verbose_name_plural': 'Activos no seriales',
            },
        ),
        migrations.CreateModel(
            name='SalidaInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actas_salida', verbose_name='Acta')),
                ('descripcion', models.TextField(max_length=500)),
                ('activos', models.ManyToManyField(to='inventario.ActivoInsumo')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Cuenta')),
                ('custodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Custodio')),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino2', to='inventario.Bodega')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen2', to='inventario.Bodega')),
            ],
            options={
                'verbose_name': 'Salida de Insumo',
                'verbose_name_plural': 'Salidas de Insumos',
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipo de piscina',
                'verbose_name_plural': 'Tipos de piscinas',
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensage', models.CharField(max_length=150, verbose_name='Mensaje')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo')),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='TrazabilidadInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensage', models.CharField(max_length=150, verbose_name='Mensaje')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ActivoInsumo')),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('actaentrada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.ActaEntrada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Cuenta')),
            ],
            bases=('inventario.actaentrada',),
        ),
        migrations.AddField(
            model_name='articuloinsumo',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Fabricante'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Fabricante'),
        ),
        migrations.AddField(
            model_name='activoinsumo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ArticuloInsumo'),
        ),
        migrations.AddField(
            model_name='activoinsumo',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='activo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Articulo'),
        ),
        migrations.AddField(
            model_name='activo',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='activo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.TipoActivo'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='activos',
            field=models.ManyToManyField(blank=True, to='inventario.Activo'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Cuenta'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='custodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Custodio'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='destino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='actasalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='actarequisicion',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='actarequisicion',
            name='central',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Central'),
        ),
        migrations.AddField(
            model_name='actaentrada',
            name='activos',
            field=models.ManyToManyField(blank=True, to='inventario.Activo'),
        ),
        migrations.AddField(
            model_name='actaentrada',
            name='custodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Custodio'),
        ),
        migrations.AddField(
            model_name='actaentrada',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_', to='inventario.Bodega'),
        ),
        migrations.AddField(
            model_name='actaentrada',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen_', to='inventario.Bodega'),
        ),
    ]
