# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'verbose_name': 'Piscina', 'verbose_name_plural': 'Piscinas'},
        ),
        migrations.AddField(
            model_name='activo',
            name='medidas',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
