# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20160319_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega'),
        ),
        migrations.AlterField(
            model_name='activoinsumo',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.Bodega'),
        ),
    ]
