# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20160319_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activoinsumo',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='articuloinsumo',
            options={'verbose_name': 'Articulo Insumo', 'verbose_name_plural': 'Aticulos de Insumos'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta de bodega', 'verbose_name_plural': 'Cuentas de bodegas'},
        ),
    ]
