# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_articulo_tiempo_entrega'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequisicionNoSerial',
            new_name='RequisicionInsumo',
        ),
        migrations.AlterModelOptions(
            name='requisicioninsumo',
            options={'verbose_name': 'Requisici\xf3n de insumo', 'verbose_name_plural': 'Requisiciones de insumos'},
        ),
    ]
