# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20160319_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicionarticulo',
            options={'verbose_name': 'Requisici\xf3n de piscina', 'verbose_name_plural': 'Requesiciones de piscina'},
        ),
        migrations.AlterField(
            model_name='requisicioninsumo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ArticuloInsumo', verbose_name='Articulo'),
        ),
    ]
