# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mantenimiento')),
            ],
            options={
                'verbose_name': 'Imagen de mantenimiento',
                'verbose_name_plural': 'Imagenes de mantenimientos',
            },
        ),
        migrations.CreateModel(
            name='ImagenRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reparacion')),
            ],
            options={
                'verbose_name': 'Imagen de reparaci\xf3n',
                'verbose_name_plural': 'Imagenes de reparaciones',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('descripcion', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('descripcion', models.TextField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='piscina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Activo', verbose_name='Piscina adquirida'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='piscinero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Piscinero'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='piscinero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Piscinero'),
        ),
        migrations.AddField(
            model_name='imagenre',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Reparacion'),
        ),
        migrations.AddField(
            model_name='imagenm',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Mantenimiento'),
        ),
    ]
