# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20160319_0441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piscinero',
            options={'verbose_name': 'Piscinero', 'verbose_name_plural': 'Piscineros'},
        ),
        migrations.AlterModelOptions(
            name='reparacion',
            options={'verbose_name': 'Reparaci\xf3n', 'verbose_name_plural': 'Reparaciones'},
        ),
        migrations.AlterModelOptions(
            name='tiporeporte',
            options={'verbose_name': 'Tipo de reporte', 'verbose_name_plural': 'Tipos de reporte'},
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
